-- Daily 3pm shop summary, generated by /api/daily-summary
CREATE TABLE IF NOT EXISTS daily_summaries (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    uuid NOT NULL REFERENCES companies ON DELETE CASCADE,
  period_start  timestamptz NOT NULL,
  period_end    timestamptz NOT NULL,
  content       text NOT NULL,
  email_sent_to text,
  created_via   text NOT NULL DEFAULT 'cron',
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS daily_summaries_company_created_idx
  ON daily_summaries (company_id, created_at DESC);

ALTER TABLE daily_summaries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "company members read summaries"
  ON daily_summaries FOR SELECT
  USING (company_id IN (SELECT company_id FROM profiles WHERE id = auth.uid()));
